### ISSUE TITLE
Should tell user to press "enter" after they are satisfied with entering the number of abilities they want to consider in the calculation

### ISSUE THREAD

**Issue by imnotaprogrammer** [NightShadeI/Revolution-Rotation-Calculator-#15]
I was a bit confused on my initial run of the program and entered 21 different abilities until I pressed "enter."

There should be a global maximum limit of how many abilities you can enter and/or it should tell you that you can press "enter" to stop entering abilities.

**Comment by NightShadeI** [comment]
Should have a fix for this in a few hours. Sorry about that!

**Comment by NightShadeI** [comment]
Should be fixed now with different input method
