### ISSUE TITLE
Possible bug in cooldown algorithm

### ISSUE THREAD

**Issue by EZtouch** [NightShadeI/Revolution-Rotation-Calculator-#19]
https://github.com/NightShadeI/Revolution-Rotation-Calculator-/blob/b786002004c1624b5295e7e8f98e07c20e9b8627/Revolution%20Rotation%20Calculator.py#L412

```
def AdjustCooldowns(Current_Buff, Adrenaline, Time):
    for Ability in TrackCooldown:
        TrackCooldown[Ability] += Time
        TrackCooldown[Ability] = round(TrackCooldown[Ability], 1)
        if TrackCooldown[Ability] >= AbilityCooldown[Ability]:
            TrackCooldown[Ability] = 0
            if Ability in ThresholdIterator and Adrenaline >= 50:
                Ready[Ability] = True
            elif Ability in UltimateIterator and Adrenaline == 100:
                Ready[Ability] = True
            else:
                Ready[Ability] = True

...
    return Current_Buff
```

@NightShadeI 
I'm not sure if I understood the algorithm properly, but it looks to me as if threshold and ultimate abilities without sufficient adrenaline will be activated because of `else: Ready[Ability] = True`
If this is indeed the case, it could be solved by replacing else with an elif to check if its a basic ability

**Comment by NightShadeI** [comment]
Think this would be the best way to fix it? - I see what you mean.
```
if Ability in ThresholdIterator:
    if Adrenaline >= 50:
        Ready[Ability] = True
elif Ability in UltimateIterator:
    if Adrenaline == 100:
            Ready[Ability] = True
else:
    Ready[Ability] = True
```

**Comment by EZtouch** [comment]
Yeah, that would work probably.
