### ISSUE TITLE
Possible miscalculation bug

### ISSUE THREAD

**Issue by EZtouch** [NightShadeI/Revolution-Rotation-Calculator-#6]
When trying to determine the optimal bar using these skills (Cleave, Dismember, Sever, Smash, Slice, Fury), the result is this:
http://runescape.wikia.com/wiki/Calculator:Revolution?cbclass=melee&hand=2&ice=0&stuns=1&slayer=0&ticks=3000&cycle=0&cycleticks=1000&anythinggoes=0&bar=Cleave%2CSmash%2CSever%2CDismember%2CFury%2CSlice

However, according to the wiki, the optimal bar should have been this:
http://runescape.wikia.com/wiki/Calculator:Revolution?cbclass=melee&hand=2&ice=0&stuns=1&slayer=0&ticks=3000&cycle=0&cycleticks=1000&anythinggoes=0&bar=Cleave%2CDismember%2CSever%2CSmash%2CSlice%2CFury

Either the wiki is wrong, or there's a bug in the algorithm, or it could be just me 🤔
Possibly helpful links:
http://runescape.wikia.com/wiki/Module:Revolution_AADPT
http://runescape.wikia.com/wiki/MediaWiki:Common.js/revocalc.js
http://runescape.wikia.com/wiki/Calculator:Revolution/Details

**Comment by NightShadeI** [comment]
The wiki calculator is flawed in a few ways, firstly its values for fury / concentrated blast are wrong and it does not take into account the boosted damage they will give (~ x 1.1 after each fully channeled usage) and although irrelevant also has incorrect values for non-slayer task tuska's wrath. You will notice if you change these values in my program it will produce EXACTLY the same output as the wiki. (Lines 13 and 21 if you wish to try)

**Comment by EZtouch** [comment]
Cool, you can close the issue 👍
